### PR TITLE
Add type-bound procedures in decomp_info

### PR DESCRIPTION
**Pull request by mathrack**

### CODE REVIEW

**Comment by pbartholomew08** [comment]
This is quite a significant change to the semantics - I think we need to discuss at the hackathon

**Comment by mathrack** [comment]
Please note that the original subroutines `decomp_info_init` and `decomp_info_finalize` are still present and usable.

**Comment by pbartholomew08** [comment]
I think one way would be better than two

**Comment by mathrack** [comment]
I have kept them to avoid breaking existing codes.

**Comment by pbartholomew08** [comment]
I think it would be best not to have a mishmash of codes - let's see what others think about the different approaches and choose one.

**Comment by mathrack** [comment]
Any update needed on this PR ?

**Comment by mathrack** [comment]
It looks like there is no interest for this PR, I will close it.

**Pull request closed without merging**
