### PR TITLE
Fix most of the examples

### PR DESCRIPTION
**Pull request by mathrack**
Compilation with gcc tested.

The file fftdata is missing in fft_test_r2c.

This should help https://github.com/xcompact3d/2decomp-fft/issues/28

### CODE REVIEW

**Comment by mathrack** [comment]
Tested with intel compiler : `make CMP=intel BUILD=debug && make CMP=intel BUILD=debug examples` is working

**Comment by rfj82982** [comment]
Hi Guys 
with Paul we added 
```
call MPI_COMM_RANK(MPI_COMM_WORLD,nrank,ierror)
call MPI_COMM_SIZE(MPI_COMM_WORLD,nproc,ierror)
```
in ` decomp_2d_init` because without this none of the examples is going to work. At the moment I cannot find this not in the main branch nor in any other.  
Cedric your branch `fix-examples` does not work with openmpi, 
```
rfj82982@ceg-rolfo-2 2decomp-fft % make FC=mpif90-openmpi-mp examples
mpif90-openmpi-mp  -cpp -fallow-argument-mismatch -O3 -march=native -J mod -Imod  -DDOUBLE_PREC -DVERSION=\"b3ad163\"  -c src/decomp_2d.f90 -o obj/decomp_2d.o
mpif90-openmpi-mp  -cpp -fallow-argument-mismatch -O3 -march=native -J mod -Imod  -DDOUBLE_PREC -DVERSION=\"b3ad163\"  -c src/d2d_log.f90 -o obj/d2d_log.o
mpif90-openmpi-mp  -cpp -fallow-argument-mismatch -O3 -march=native -J mod -Imod  -DDOUBLE_PREC -DVERSION=\"b3ad163\"  -c src/./glassman.f90 -o obj/./glassman.o
mpif90-openmpi-mp  -cpp -fallow-argument-mismatch -O3 -march=native -J mod -Imod  -DDOUBLE_PREC -DVERSION=\"b3ad163\"  -c src/fft_generic.f90 -o obj/fft_generic.o
ar rcs libdecomp2d.a obj/decomp_2d.o obj/d2d_log.o obj/./glassman.o obj/fft_generic.o
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C examples
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C test2d test2d
mpif90-openmpi-mp   -cpp -fallow-argument-mismatch -O3 -march=native -J mod -I../../mod -c test2d.f90
f951: Warning: Nonexistent include directory 'mod' [-Wmissing-include-dirs]
mpif90-openmpi-mp -o test2d test2d.o -L../../ -ldecomp2d
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
make[2]: *** [test2d] Error 1
make[1]: *** [test2d] Error 2
make: *** [examples] Error 2
```

In my case works (i.e. build) only with mpich. Later on I’ll try to fix and start to run some tests.

**Comment by pbartholomew08** [comment]
It looks like something has gone wrong with the `mod` directories, although strange that it would be ok with MPICH... Let me try here what's happening

**Comment by pbartholomew08** [comment]
It's the space between `J` and `$(MODDIR)`, I think I have a fix...

**Comment by mathrack** [comment]
@rfj82982 are you talking about the commit below ?

https://github.com/mathrack/2decomp-fft/commit/67931a2b6cb28dd538cadcc15acb67f6e5165917

**Comment by mathrack** [comment]
@pbartholomew08 the space was added at some point for the intel compiler

**Comment by pbartholomew08** [comment]
yes, although I don't know why as I have a space in the variable definition unless someone stripped it, i.e. the variable was defined as `MODFLAG = -module ` (note space at the end of line).

**Comment by pbartholomew08** [comment]
Assuming the space is the issue it should (I think) be fixed by #38

**Comment by pbartholomew08** [comment]
@rfj82982 which compiler are you wrapping with mpif90? Using the same command line you show it complains about non-existant `mod` dir when building examples (see above), however it does build with mpif90+gfortran-9.4

**Comment by rfj82982** [comment]
In my case I have gnu 12.1 on Mac. The same that I am using also with mpich and in that case I have only warnings but i have all the executables

```
rfj82982@ceg-rolfo-2 2decomp-fft % mpif90-openmpi-mp -v              
Using built-in specs.
COLLECT_GCC=/opt/local/bin/gfortran-mp-devel
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/aarch64-apple-darwin21/12.1.0/lto-wrapper
Target: aarch64-apple-darwin21
Configured with: /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_gcc-devel/gcc-devel/work/gcc-12-branch-a613c586b5461d7fb99fa076ef7e59eca4227fae/configure --prefix=/opt/local --build=aarch64-apple-darwin21 --enable-languages=c,c++,objc,obj-c++,lto,fortran,jit --libdir=/opt/local/lib/gcc-devel --includedir=/opt/local/include/gcc-devel --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-devel --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-devel --with-gxx-include-dir=/opt/local/include/gcc-devel/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --with-zstd=/opt/local --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-build-config=bootstrap-debug --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --enable-host-shared --with-gxx-libcxx-include-dir=/opt/local/libexec/llvm-13/include/c++/v1 --with-pkgversion='MacPorts gcc-devel 12-20220615_0+enable_stdlib_flag' --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.1.0 (MacPorts gcc-devel 12-20220615_0+enable_stdlib_flag) 
```

**Comment by pbartholomew08** [comment]
> In my case I have gnu 12.1 on Mac. The same that I am using also with mpich and in that case I have only warnings but i have all the executables
> 

ok - I'll try again later on a different computer/compiler

**Comment by mathrack** [comment]
One day, we will have automatic tests for compilation for more compilers / MPI library ! See this [PR](https://github.com/xcompact3d/Incompact3d/pull/113) for a way to have automatic tests with both gnu and intel compilers.

**Comment by mathrack** [comment]
@rfj82982 could you add a MacOs build in the following PR ? https://github.com/xcompact3d/2decomp-fft/pull/39

It should be possible : [https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

**Comment by mathrack** [comment]
The example test2d is looking slightly better now.

Please note that the present PR could use the one looking at the debug level : https://github.com/xcompact3d/2decomp-fft/pull/35/files

**Comment by pbartholomew08** [comment]
The above commit - `Add a "memory" to Makefile execution...` creates a file `Makefile.settings` with your FFLAGS, etc. and includes this on subsequent runs - anything you specify will overwrite this. @mathrack can you check this does what you wanted?

**Comment by mathrack** [comment]
After a quick test it seems to work as expected for a debug build GNU + MPICH, thank you @pbartholomew08

**Comment by pbartholomew08** [comment]
I have a feeling there will be ways to break it so raise any issues you experience. I forgot to say, ``make clean`` will also remove the settings file

**Comment by pbartholomew08** [comment]
Halo test now runs in memory and calls MPI_Abort with non-zero error code on failure

**Comment by mathrack** [comment]
I suspect halo subroutines are broken. For instance here :  

https://github.com/mathrack/2decomp-fft/blob/fix_examples/src/halo_common.f90#L32

If nproc = 1, the data can be in y-pencil or z-pencil, the test will claim it is using x-pencil. More generally, if the data is in y-pencil and p_row = 1, the test will claim it is using x-pencil.

**Comment by pbartholomew08** [comment]
that's how that code has always been, I'm not sure how we could fix it without breaking use cases

**Comment by pbartholomew08** [comment]
However we can at the very least update the test to try and check whether it does break in those circumstances

**Comment by mathrack** [comment]
I think the update_halo subroutine needs one more argument to clarify the pencil orientation of the given array. On this ground, we can add some check on `p_row` and `p_col` to make sure the indices are not out of bound.

To fix this, we need feedback from people using this halo subroutine.

**Comment by mathrack** [comment]
This PR will be closed. Work will resume in the branch https://github.com/xcompact3d/2decomp-fft/tree/fix_examples after https://github.com/xcompact3d/2decomp-fft/pull/42 is merged.

**Pull request closed without merging**
