### PR TITLE
Build test cases under strictrer (BUILD=debug/dev) flags

### PR DESCRIPTION
**Pull request by pbartholomew08**
This prevents test building failing when stricter debug flags are enabled

### CODE REVIEW

**Comment by mathrack** [comment]
Currently, the test cases do not contain case-specific modules or submodules. Thus, there is no need for creating a folder, it is going to stay empty...

**Comment by mathrack** [comment]
I suggest the following fix : 
[patch.txt](https://github.com/xcompact3d/2decomp-fft/files/9622721/patch.txt)

**Comment by mathrack** [comment]
I will try that but it would be easier to merge the automatic compilation to check proper compilation with gnu / intel  / nvidia

**Comment by pbartholomew08** [comment]
I think if `$(MODFLAG)` works with GNU we can assume it works with others and fix later if not

**Comment by pbartholomew08** [comment]
Or we make an empty directory ;)

**Comment by pbartholomew08** [comment]
@mathrack this should be ready now - it builds examples under `BUILD=dev` with GNU and Intel compilers

**Review by mathrack — APPROVED** [review]

**Pull request merged**
