### PR TITLE
Update CMake scripts and README to help linking against fftw3.

### PR DESCRIPTION
**Pull request by mathrack**

### CODE REVIEW

**Review by pbartholomew08 — DISMISSED** [review]
LGTM!

**Comment by rfj82982** [comment]
Hi Guys 
I’ll have a look at this tonight. 

Ciao

**Comment by mathrack** [comment]
Hello, I think this is ready for merging. Please let me know if some modification is needed.

**Comment by pbartholomew08** [comment]
How does `FFTW_DOUBLE_LIB_FOUND` interact with `DOUBLE_PRECISION`? Should one block the other?

**Comment by mathrack** [comment]
I think the variables `FFTW_DOUBLE_LIB_FOUND` and `FFTW_FLOAT_LIB_FOUND` control the link flags `-lfftw3` and `-lfftw3f`. The fftw3 library for single precision and double precision is not the same. Decomp2d should pick the correct one because the argument provided will be float or double.

**Comment by mathrack** [comment]
I had a fftw3 build limited to double precision. Without the present PR, the examples do not compile because they try to link with the float version of fftw3.

**Comment by pbartholomew08** [comment]
I mean, should asking for DOUBLE_PREC and getting FFTW_FLOAD_LIB_FOUND be rejected by the build system? Otherwise looks good to me!

**Review by pbartholomew08 — APPROVED** [review]

**Comment by rfj82982** [comment]
I tested fft_f03 and everything seems to work. I’ll approve it now

**Pull request merged**
