### PR TITLE
Update transpose for slabs

### PR DESCRIPTION
**Pull request by rfj82982**
Third PR to perform a memory copy rather than a transpose operation via communication (MPI/NCCL) in case of slabs.

### CODE REVIEW

**Comment by pbartholomew08** [comment]
Marking as draft as I think dependent on #160 (and maybe #161?)

**Comment by rfj82982** [comment]
This should be the last PR to have decomp2d ready to be released.

**Review by mathrack — APPROVED** [review]

**Comment by mathrack** [comment]
I will merge. A last PR is needed to prettify the code before release.

**Comment by rfj82982** [comment]
OK no problem. To be complete we should look into pointers to do complex transpose, but we might do this more generally and save about 1/3 of the memory footprint.

**Comment by mathrack** [comment]
@rfj82982 there is also some potential for memory saving using in the FFT engine :

- [in-place r2c and c2r](https://github.com/xcompact3d/2decomp-fft/pull/144) transforms
- reduced memory requirement if only r2c / c2r transforms are used and no c2c transform is needed

**Pull request merged**
